[package]
name = "day13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { version = "0.13.0" }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
